language: python
python:
  - 2.7
  - 3.4
env:
  - DJANGO=1.6.11
  - DJANGO=1.7.10
  - DJANGO=1.8.4
install:
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - pip install -r tests/requirements.txt
  - python setup.py -q install
after_success:
  - coveralls --verbose
script:
  - coverage run --source=django_hitcounter manage.py test
