language: python
python:
- 3.5
sudo: false
env:
- TOXENV=py27-django17
- TOXENV=py27-django18
- TOXENV=py27-django19
- TOXENV=py34-django17
- TOXENV=py34-django18
- TOXENV=py34-django19
- TOXENV=py35-django19
install:
- pip install -q tox
script:
- tox
deploy:
  provider: pypi
  user: MrYoda
  password:
    secure: NBQTNXG6UrsEvVmLSrC4ZXNHZ9lEigFDbNzkUonVZcGDEgD+QlQULscJxlhrJCuorwZYxNRRaLubkYqnFtuD98gfVwBQ6MSSYUVNF2HjS/tqb+N+G6sxMW1yNGyEsuSqZwlV7KPZcrtScadnJf9VVN+yOYioA1hg7lAjuOyRuhVzJCVCp/9CEABwEaOH2iJYVt+MOtAk0KiFZf1xy3r6ZF3iO+d8QzAyKTtti1Xt389ugNJ4HBSeh6QtuMVxluOM0tYipnQ/NUguLb6BsRWqDMatUZezGpJNZwQ04ZwPf8xTiYXDK+0OibHSONdS1XT13stOzhGFoRBrBGy4fgBSkSyeXk44/ZDCoAkLjgOMrTGilEa5/Q39j1LOha1/HqD1XWLu8ffVmbz/fr2NILpgVve/6ZZ7w1NRNUP9qrYP0von+M/FH2WBX6TL9nYFvJBqOhoegiMQvSS9ThZxmIaJ36EF/WOnjKbFl2oGQ9mGVlsojYOPAZLwkSNsbkHayKbbgYrVDr6yQDysBuDjKvL2RLqedolZEY7Sxp+pLqF8rb0M8ZxibeiqnC4GoiJeL8KWMLC2pPHMrST3zOadXbiW8rFcleyqBdsPiaOmSfmtQzLo+gekaAaEpMxjM8tT9qgdYAXGKT+bprKUo7LyezoMncsVCXpBvgm1bizEwjJWL+4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: DirectlineDev/django-hitcounter
